services:
  - type: web
    name: watchmate-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && cd watchmate && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd watchmate && gunicorn watchmate.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: watchmate-db
          property: connectionString

databases:
  - name: watchmate-db
    plan: free
    region: oregon