# Generated by Django 5.2.6 on 2025-10-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_remove_review_avg_rating_remove_review_number_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='poster',
            field=models.URLField(blank=True, help_text='URL to poster image'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('review_user', 'watchlist')},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='watchlist.genre'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer'), ('producer', 'Producer')], max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='watchlist.watchlist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='watchlist.person')),
            ],
            options={
                'ordering': ['order', 'person__name'],
                'unique_together': {('person', 'watchlist', 'role', 'character_name')},
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Currently Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_watchlist', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist')),
            ],
            options={
                'ordering': ['-added_date'],
                'unique_together': {('user', 'watchlist')},
            },
        ),
    ]
